stages:
  - build
  - build_image

build:development:
  stage: build
  image: node:lts
  tags:
    - docker
  only:
    - dev
  except:
    - master
  script:
    - npm install --prod
    - npm install -D typescript @angular/cli @angular/compiler
    - npm run build:dev
  artifacts:
    paths:
      - dist

build_image:development:
  stage: build_image
  image: docker:dind
  tags:
    - docker
  only:
    - dev
  dependencies:
    - build:development
  script:
    - docker login -u $CI_USER -p $CI_REGISTRY_TOKEN $CI_REGISTRY
    - docker build -t registry.gitlab.com/fiit_coworking/e-library/e-library-client:dev .
    - docker push registry.gitlab.com/fiit_coworking/e-library/e-library-client:dev

build:prod:
  stage: build
  image: node:lts
  tags:
    - docker
  only:
    - master
    - merge_requests
  script:
    - npm install --prod
    - npm install -D typescript @angular/cli @angular/compiler
    - npm run build:prod
  artifacts:
    paths:
      - dist

build_image:prod:
  stage: build_image
  image: docker:dind
  tags:
    - docker
  only:
    - master
  dependencies:
    - build:prod
  script:
    - docker login -u $CI_USER -p $CI_REGISTRY_TOKEN $CI_REGISTRY
    - docker build -t registry.gitlab.com/fiit_coworking/e-library/e-library-client:prod .
    - docker push registry.gitlab.com/fiit_coworking/e-library/e-library-client:prod
