stages:
  - build
  - build_image

build:development:
  stage: build
  image: node:14
  tags:
    - docker
  only:
    - dev
  except:
    - master
  script:
    - npm install --prod
    - npm install -D typescript @angular/cli @angular/compiler
    - npm run build:dev
  artifacts:
    paths:
      - dist
    expire_in: 2 hours



build_image:development:
  stage: build_image
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  tags:
    - docker
    - build_docker
  only:
    - dev
  dependencies:
    - build:development
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:dev

build:prod:
  stage: build
  image: node:14
  tags:
    - docker
  only:
    - master
    - merge_requests
  script:
    - npm install --prod
    - npm install -D typescript @angular/cli @angular/compiler
    - npm run build:prod
  artifacts:
    paths:
      - dist
    expire_in: 2 hours

build_image:prod:
  stage: build_image
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  tags:
    - docker
  only:
    - master
  dependencies:
    - build:prod
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:prod
