stages:
  - build
  - deploy

build:
  stage: build
  image: node:22
  script:
    - npm i --save-dev
    - npm run build:dev
  artifacts:
    name: "$ENVIRONMENT-$CI_COMMIT_SHORT_SHA"
    expire_in: 15 minute
    paths:
      - dist/
  environment:
    name: ${ENVIRONMENT}
  only:
    - dev
    - master
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
      variables:
        - ENVIRONMENT: ["elvira.fiit.stuba.sk"]
    - if: '$CI_COMMIT_REF_NAME == "develop"'
      variables:
        - ENVIRONMENT: ["dev.elvira.fiit.stuba.sk"]

deploy:
  stage: deploy
  image: ghcr.io/backbonesk/node-deployer:master
  variables:
    GIT_STRATEGY: none
    BUILD_DIR: dist/
  script:
    - NODE_PATH=/usr/local/lib/node_modules node /opt/node-deployer/deploy.js
  environment:
    name: dev
    url: https://elvira-dev.fiit.stuba.sk/
  only:
    - dev
    - master
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
      variables:
        - ENVIRONMENT: ["elvira.fiit.stuba.sk"]
    - if: '$CI_COMMIT_REF_NAME == "develop"'
      variables:
        - ENVIRONMENT: ["dev.elvira.fiit.stuba.sk"]