stages:
  - dependencies
  - build
  - deploy

install dependencies:
  stage: dependencies
  image: node:22
  script:
    - npm i --save-dev
  artifacts:
    paths:
      - node_modules
  only:
    - dev

build dev:
  stage: build
  image: node:22
  script:
    - mkdir -p _build
    - npm run build:prod
    - mv dist _build/$ENVIRONMENT
  artifacts:
    name: "$ENVIRONMENT-$CI_COMMIT_SHORT_SHA"
    paths:
      - _build/$ENVIRONMENT
  environment: $ENVIRONMENT
  parallel:
    matrix:
      - ENVIRONMENT: [ fiit, fiit-dev, mtf, svf, fei ]
  only:
    - dev

deploy:
  stage: deploy
  image: ghcr.io/backbonesk/node-deployer:master
  variables:
    GIT_STRATEGY: none
    BUILD_DIR: _build/$ENVIRONMENT
  script:
    - NODE_PATH=/usr/local/lib/node_modules node /opt/node-deployer/deploy.js
  environment:
    name: dev
    url: https://elvira-dev.fiit.stuba.sk/
  only:
    - dev