stages:
  - dependencies
  - build
  - deploy

install dependencies:
  stage: dependencies
  image: node:22
  script:
    - npm i --save-dev
  artifacts:
    paths:
      - node_modules
  only:
    - dev
    - master  # Include master if needed

# Job template for build
.build_template:
  stage: build
  image: node:22
  script:
    - mkdir -p _build
    - npm run build:prod
    - mv dist _build/$ENVIRONMENT
  artifacts:
    name: "$ENVIRONMENT-$CI_COMMIT_SHORT_SHA"
    paths:
      - _build/$ENVIRONMENT
  environment: $ENVIRONMENT

# Build job for 'dev' branch
build dev:
  extends: .build_template
  parallel:
    matrix:
      - ENVIRONMENT: [fiit-dev]
  only:
    - dev

# Build job for 'master' branch
build production:
  extends: .build_template
  parallel:
    matrix:
      - ENVIRONMENT: [fad, fchpt, fei, fiit, mtf, sjf, svf]
  only:
    - master

# Job template for deploy
.deploy_template:
  stage: deploy
  image: ghcr.io/backbonesk/node-deployer:master
  variables:
    GIT_STRATEGY: none
    BUILD_DIR: _build/$ENVIRONMENT
  script:
    - NODE_PATH=/usr/local/lib/node_modules node /opt/node-deployer/deploy.js
  environment: $ENVIRONMENT

# Deploy job for 'dev' branch
deploy dev:
  extends: .deploy_template
  parallel:
    matrix:
      - ENVIRONMENT: [fiit-dev]
  only:
    - dev

# Deploy job for 'master' branch
deploy production:
  extends: .deploy_template
  parallel:
    matrix:
      - ENVIRONMENT: [fad, fchpt, fei, fiit, mtf, sjf, svf]
  only:
    - master
