stages:
  - build
  - deploy

build dev:
  stage: build
  image: node:20
  script:
    - npm i --save-dev
    - npm run build:dev
  artifacts:
    name: "elvira-dev-$CI_COMMIT_SHORT_SHA"
    expire_in: 15 minute
    paths:
      - dist/elibrary-portal/
  environment:
    name: dev
    url: https://elvira-dev.fiit.stuba.sk/
  only:
    - dev
